--------------------------------------------------------
--  File created - Tuesday-December-16-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table A
--------------------------------------------------------

  CREATE TABLE "TRANSPORT"."A" 
   (	"A_SEQ" NUMBER, 
	"RELATION_SEQ" NUMBER, 
	"DIRECTION" VARCHAR2(3), 
	"STATUS" VARCHAR2(15), 
	"ARECORD" VARCHAR2(1), 
	"CONSTANT" VARCHAR2(3), 
	"WAYBILL_NUMBER" VARCHAR2(18), 
	"WAYBILL_DATE" VARCHAR2(8), 
	"TRANSPORT_TYPE" VARCHAR2(1), 
	"SEQUENTIAL_VEHICLE_NR" VARCHAR2(2), 
	"SENDING_DEPOT_ID" VARCHAR2(10), 
	"FREIGHT_OPERATOR_NAME" VARCHAR2(13), 
	"POSTCODE_FREIGHT_OPERAT" VARCHAR2(9), 
	"FREIGHT_OPERATOR_PLACE" VARCHAR2(12), 
	"LOADING_UNITS_NO1" VARCHAR2(15), 
	"LOADING_UNITS_NO2" VARCHAR2(15), 
	"LEAD_SEAL_NUMBER_1" VARCHAR2(10), 
	"LEAD_SEAL_NUMBER_2" VARCHAR2(10), 
	"RELEASE6" VARCHAR2(1), 
	"HEADER_LINE" VARCHAR2(128), 
	"FTP_SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITONITY_DATA" ;
